apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: gluster-test
 annotations:
   volume.beta.kubernetes.io/storage-class: heketi-storage
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 1Gi
